# Utiliza una imagen base de Python
FROM python:3.10

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia los archivos de la aplicación Flask al directorio de trabajo
COPY .. .

# Instala las dependencias de la aplicación Flask

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
# Expone el puerto en el que se ejecutará la aplicación Flask
EXPOSE 5000
