version: '3'
services:

  flask-app:
    build:
      dockerfile: ./docker/Dockerfile.flask
    command: bash -c "flask run"
    container_name: USMT-App
    image: usmt-flask
    environment:
      FLASK_APP: web
      FLASK_DEBUG: false
      FLASK_RUN_PORT: 5000
      FLASK_RUN_HOST: 0.0.0.0
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: UrbanStreetMappingTransfer
      JWT_SECRET_KEY: CLAVEJWTUSMT
      DEFAULT_USER: admin
      DEFAULT_PASSWORD: USMT
      SECRET_KEY: Mistral
    ports:
      - "5000:5000"
    depends_on:
      - neo4j

  neo4j:
    build:
      dockerfile: ./docker/Dockerfile.neo4j
    image: usmt-neo4j
    container_name: USMT-BBDD
    ports:
      - "7474:7474"
      - "7687:7687"
